// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:860359746569:web:cf7dcb54d5ac7f936e44d8',
    messagingSenderId: '860359746569',
    projectId: 'tsec-hacks-25',
    authDomain: 'tsec-hacks-25.firebaseapp.com',
    storageBucket: 'tsec-hacks-25.firebasestorage.app',
    measurementId: 'G-BPG16WQHBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmgdreXAQLGnftR0njpwhJMDxkKFx2Fg',
    appId: '1:860359746569:android:1efaed109a66f84b6e44d8',
    messagingSenderId: '860359746569',
    projectId: 'tsec-hacks-25',
    storageBucket: 'tsec-hacks-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjPaUdZDk325pAaUHKPZ6823VdW357fs',
    appId: '1:860359746569:ios:7e7dcdf1b0e7fe046e44d8',
    messagingSenderId: '860359746569',
    projectId: 'tsec-hacks-25',
    storageBucket: 'tsec-hacks-25.firebasestorage.app',
    iosBundleId: 'com.htxsins.person',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjPaUdZDk325pAaUHKPZ6823VdW357fs',
    appId: '1:860359746569:ios:7e7dcdf1b0e7fe046e44d8',
    messagingSenderId: '860359746569',
    projectId: 'tsec-hacks-25',
    storageBucket: 'tsec-hacks-25.firebasestorage.app',
    iosBundleId: 'com.htxsins.person',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYQYOFy6Y-N1q5xKtUFyU2PziMq7NRfM',
    appId: '1:860359746569:web:5d33716380f7f9286e44d8',
    messagingSenderId: '860359746569',
    projectId: 'tsec-hacks-25',
    authDomain: 'tsec-hacks-25.firebaseapp.com',
    storageBucket: 'tsec-hacks-25.firebasestorage.app',
    measurementId: 'G-BC0F6MEBTV',
  );
}
